nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.0.0.cjs

npmScopes:
  dxp:
    npmRegistryServer: https://int.repositories.cloud.sap/artifactory/api/npm/proxy-deploy-releases-hyperspace-npm
